import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/provider/ThemeProvider";
import TopBar from "@/components/customUi/TopBar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/customUi/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <SidebarProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* ✅ TopBar ثابت */}
            <header className="fixed top-0 left-0 right-0 z-30 h-16 bg-white dark:bg-gray-900 shadow flex items-center justify-between px-4">
              <TopBar />
            </header>

            {/* ✅ المحتوى بعد التوب بار */}
            <div className="flex pt-16 min-h-screen">
              {/* ✅ المحتوى الرئيسي ياخد المساحة المتبقية من السايد بار */}
              <main className="flex-1 p-4 overflow-y-auto">{children}</main>

              {/* ✅ السايد بار على اليمين وتحت التوب بار */}
              <AppSidebar className="hidden md:block fixed top-16 right-0 z-20 w-64 h-[calc(100vh-64px)] bg-white dark:bg-gray-900 shadow-md" />
            </div>

            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  fontSize: "17px",
                  padding: "14px 20px",
                },
              }}
            />
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
